// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	m := map[int]string{1: "one", 2: "two"}
	v, ok := m[1]
	fmt.Println(v, ok)
	_, ok2 := m[9]
	fmt.Println(ok2)
	delete(m, 1)
	fmt.Println(len(m))
}
