// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	var big uint64 = 1 << 63
	var small uint64 = 5
	fmt.Println(big > small)
	fmt.Println(big / 2)
	fmt.Println(uint32(4000000000) > uint32(5))
	var x uint = 3
	x -= 5
	fmt.Println(x > 1000)
}
