// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	a, b := 0xF0, 0x3C
	fmt.Println(a&b, a|b, a^b, a&^b)
	fmt.Println(^a)
	count := 0
	for x := 0x5A; x != 0; x &= x - 1 {
		count++
	}
	fmt.Println(count)
}
