// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	fmt.Println(1<<10, 1024>>3)
	var v int64 = -8
	fmt.Println(v >> 1)
	var u uint64 = 1 << 62
	fmt.Println(u<<1, u>>61)
	n := 4
	fmt.Println(1<<n, 256>>n)
}
