// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	fmt.Println(withDefer())
}

func withDefer() (result int) {
	defer func() { result *= 2 }()
	result = 21
	return result
}
