// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	pairs := [][2]int{{7, 3}, {-7, 3}, {7, -3}, {-7, -3}}
	for _, p := range pairs {
		fmt.Println(p[0]/p[1], p[0]%p[1])
	}
}
