// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	fns := make([]func() int, 0, 3)
	for i := 0; i < 3; i++ {
		fns = append(fns, func() int { return i })
	}
	for _, f := range fns {
		fmt.Println(f())
	}
}
