// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	a, b := 1, 2
	a, b = b, a
	fmt.Println(a, b)
	steps := 0
outer:
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			steps++
			if i*j == 6 {
				break outer
			}
			if j == 2 {
				continue outer
			}
		}
	}
	fmt.Println(steps)
}
