// Code generated by gencorpus; DO NOT EDIT.
package main

import (
	"errors"
	"fmt"
)

func main() {
	_, err := lookup(0)
	if errors.Is(err, errNotFound) {
		fmt.Println("not found")
	}
	v, err := lookup(2)
	if err == nil {
		fmt.Println("ok", v)
	}
}

var errNotFound = errors.New("not found")

func lookup(i int) (int, error) {
	if i == 0 {
		return 0, errNotFound
	}
	return i * 10, nil
}
