// Code generated by gencorpus; DO NOT EDIT.
package main

import (
	"fmt"
	"sort"
)

func main() {
	m := map[string]int{}
	words := []string{"a", "b", "a", "c", "b", "a"}
	for _, w := range words {
		m[w]++
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Println(k, m[k])
	}
}
