// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	fmt.Println(gmax(3, 7))
	fmt.Println(gmax("apple", "banana"))
	fmt.Println(gmin(3, 7))
}

type ordered interface {
	~int | ~string
}

func gmax[T ordered](a, b T) T {
	if a > b {
		return a
	}
	return b
}

func gmin[T ordered](a, b T) T {
	if a < b {
		return a
	}
	return b
}
