// Code generated by gencorpus; DO NOT EDIT.
package main

import (
	"fmt"
	"strconv"
)

func main() {
	v, err := strconv.ParseInt("-9000", 10, 64)
	fmt.Println(v, err == nil)
	u, uerr := strconv.ParseUint("123", 10, 64)
	fmt.Println(u, uerr == nil)
	_, bad := strconv.ParseUint("-1", 10, 64)
	fmt.Println(bad != nil)
	b, _ := strconv.ParseBool("true")
	fmt.Println(b)
}
