// Code generated by gencorpus; DO NOT EDIT.
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Printf("%.6f\n", math.Pow(2, 0.5))
	fmt.Printf("%.6f\n", math.Pow(2.0, 10.0))
	fmt.Printf("%.6f\n", math.Sqrt(2))
	fmt.Printf("%.6f\n", math.Exp(1))
	fmt.Printf("%.6f\n", math.Log(math.E))
	fmt.Printf("%.6f\n", math.Log10(1000))
	fmt.Printf("%.6f\n", math.Sin(1))
	fmt.Printf("%.6f\n", math.Cos(1))
	fmt.Printf("%.6f\n", math.Tan(1))
	fmt.Printf("%.6f\n", math.Atan2(1, 1))
	fmt.Printf("%.6f\n", math.Asin(0.5))
	fmt.Printf("%.6f\n", math.Hypot(3, 4))
	fmt.Printf("%.6f\n", math.Exp2(10))
	fmt.Printf("%.6f\n", math.Log2(8))
}
