// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	fmt.Println(run())
}

func run() int {
	sum := 0
	for i := 0; i < 4; i++ {
		defer func(v int) { sum += v }(i)
	}
	// Defers haven't run yet here; they fire after the return value is fixed.
	return collect()
}

func collect() int {
	n := 0
	defer func() { n = 99 }()
	return n
}
