// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	fmt.Println(scores["alice"], scores["bob"], len(scores))
	scores["carol"] = 3
	fmt.Println(len(scores))
}

var scores = map[string]int{"alice": 1, "bob": 2}

func init() {
	scores["alice"]++
}
