// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	report(true)
	report(false)
}

func report(c bool) {
	if c {
		defer fmt.Println("cleanup")
	}
	fmt.Println("work", c)
}
