// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	var a int8 = 127
	a++
	var b uint8 = 255
	b++
	var c int16 = 32767
	c++
	var d uint16 = 65535
	d++
	var e int32 = 2147483647
	e++
	fmt.Println(a, b, c, d, e)
	p, q := uint8(200), uint8(100)
	fmt.Println(p + q)
}
