// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	type point struct{ x, y int }
	p := point{1, 2}
	q := p
	q.x = 9
	fmt.Println(p.x, q.x)
	pts := []point{{1, 1}, {2, 2}}
	for _, v := range pts {
		v.y = 0
	}
	fmt.Println(pts[0].y, pts[1].y)
}
