// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	fmt.Println(sum("three", 1, 2, 3))
	fmt.Println(sum("none"))
	s := []int{4, 5}
	fmt.Println(sum("spread", s...))
}

func sum(label string, xs ...int) int {
	t := 0
	for _, x := range xs {
		t += x
	}
	fmt.Println(label, len(xs))
	return t
}
