// Code generated by gencorpus; DO NOT EDIT.
package main

import (
	"errors"
	"fmt"
)

func main() {
	fmt.Println(errA.Error())
	if errA != errB {
		fmt.Println("distinct")
	}
	fmt.Println(counter())
	fmt.Println(counter())
}

var errA = errors.New("alpha")
var errB = errors.New("beta")
var calls = 0

func counter() int {
	calls++
	return calls
}
