// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	fmt.Println(describe(7), describe("hi"), describe(false), describe([]int{1, 2}), describe(3.5))
}

func describe(v interface{}) string {
	switch x := v.(type) {
	case int:
		return fmt.Sprintf("int:%d", x)
	case string:
		return "str:" + x
	case bool:
		if x {
			return "bool:t"
		}
		return "bool:f"
	case []int:
		return fmt.Sprintf("slice:%d", len(x))
	default:
		return "other"
	}
}
