// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	funcs := []func() int{}
	for i := 0; i < 3; i++ {
		funcs = append(funcs, func() int { return i })
	}
	for _, f := range funcs {
		fmt.Println(f())
	}
}
