// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	type rec struct {
		name string
		hits int
	}
	m := map[int]rec{}
	m[1] = rec{"a", 10}
	m[2] = rec{"b", 20}
	m[1] = rec{"a2", 11}
	v, ok := m[1]
	fmt.Println(v.name, v.hits, ok)
	_, miss := m[9]
	fmt.Println(miss)
	delete(m, 1)
	fmt.Println(len(m))
	w := m[2]
	fmt.Println(w.name, w.hits)
	m[3] = rec{"c", 30}
	fmt.Println(len(m), m[3].name)
}
