// Code generated by gencorpus; DO NOT EDIT.
package main

import (
	"errors"
	"fmt"
)

func main() {
	base := errors.New("base failure")
	wrapped := fmt.Errorf("operation failed: %w", base)
	fmt.Println(wrapped.Error())
	if errors.Is(wrapped, base) {
		fmt.Println("is base")
	}
	fmt.Println(errors.Unwrap(wrapped).Error())
}
