// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	a := [3]int{1, 2, 3}
	b := a
	b[0] = 99
	fmt.Println(a[0], b[0])
	mutate(a)
	fmt.Println(a[1])
}

func mutate(arr [3]int) {
	arr[1] = 42
}
