// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	in := []int{1, 2, 3, 4, 5}
	doubled := mapper(in, func(x int) int { return x * 2 })
	sum := 0
	for _, v := range doubled {
		sum += v
	}
	fmt.Println(sum)
	evens := filter(in, func(x int) bool { return x%2 == 0 })
	fmt.Println(len(evens), evens[0], evens[1])
}

func mapper[T, U any](s []T, f func(T) U) []U {
	out := make([]U, len(s))
	for i, v := range s {
		out[i] = f(v)
	}
	return out
}

func filter[T any](s []T, keep func(T) bool) []T {
	var out []T
	for _, v := range s {
		if keep(v) {
			out = append(out, v)
		}
	}
	return out
}
