// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	var m [4][3]int
	for i := 0; i < 4; i++ {
		for j := 0; j < 3; j++ {
			m[i][j] = i*3 + j
		}
	}
	total := 0
	for i := 0; i < 4; i++ {
		for j := 0; j < 3; j++ {
			total += m[i][j]
		}
	}
	fmt.Println(total, m[3][2], m[0][0])
}
