// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	in := make(chan int, 8)
	out := make(chan int, 8)
	go worker(in, out)
	for i := 1; i <= 5; i++ {
		in <- i
	}
	close(in)
	total := 0
	for i := 0; i < 5; i++ {
		total += <-out
	}
	fmt.Println(total)
}

func worker(in <-chan int, out chan<- int) {
	for v := range in {
		out <- v * v
	}
}
