// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	grid := make([][]int, 3)
	for i := range grid {
		grid[i] = make([]int, 3)
		for j := range grid[i] {
			grid[i][j] = i*3 + j
		}
	}
	total := 0
	for _, row := range grid {
		for _, v := range row {
			total += v
		}
	}
	fmt.Println(total)
}
