// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	s := []int{10, 20, 30, 40, 50}
	a := s[1:4]
	fmt.Println(len(a), a[0], a[2])
	b := s[:2]
	fmt.Println(len(b), b[1])
}
