// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	total := 0
	for _, v := range primes {
		total += v
	}
	fmt.Println(total, len(primes), names[1])
}

var primes = []int{2, 3, 5, 7, 11}
var names = []string{"zero", "one", "two"}

func init() {
	names = append(names, "three")
}
