// Code generated by gencorpus; DO NOT EDIT.
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Printf("%.6f %.6f %.6f\n", math.Sinh(1), math.Cosh(1), math.Tanh(1))
	fmt.Printf("%.6f %.6f %.6f\n", math.Asinh(1), math.Acosh(2), math.Atanh(0.5))
	fmt.Printf("%.6f %.6f\n", math.Expm1(1), math.Log1p(1))
	fmt.Printf("%.6f %.6f\n", math.Cbrt(27), math.Cbrt(-8))
	fmt.Printf("%.6f %.6f\n", math.Pow10(3), math.Ldexp(0.5, 4))
}
