// Code generated by gencorpus; DO NOT EDIT.
package main

import (
	"fmt"
	"strconv"
)

func main() {
	for _, s := range []string{"42", "-7", "+9", "007", "", "abc", "1x", " 3"} {
		n, err := strconv.Atoi(s)
		if err != nil {
			fmt.Println("err:", err.Error())
		} else {
			fmt.Println("ok:", n)
		}
	}
	fmt.Println(strconv.Itoa(-12345))
	fmt.Println(strconv.FormatInt(255, 16), strconv.FormatInt(8, 2))
}
