// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	counter := func() func() int {
		n := 0
		return func() int { n++; return n }
	}()
	fmt.Println(counter())
	fmt.Println(counter())
	fmt.Println(counter())
}
