// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	x := 5
	defer fmt.Println("captured", x)
	x = 9
	s := "hi"
	defer fmt.Println(s, x)
	s = "bye"
	fmt.Println("body", s, x)
}
