// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	fmt.Println(run())
}

func run() (out int) {
	defer func() {
		recover()
		out = -1
	}()
	for i := 1; i <= 3; i++ {
		defer func(v int) { fmt.Println("undo", v) }(i)
	}
	panic("stop")
}
