// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	var a [3][3]int
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			a[i][j] = i*3 + j
		}
	}
	sum := 0
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			sum += a[i][j]
		}
	}
	fmt.Println(sum, a[2][2], a[0][0])
}
