// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	type buf struct {
		n    int
		data [4]int
	}
	var b buf
	for i := 0; i < 4; i++ {
		b.data[i] = i * i
		b.n++
	}
	c := b
	c.data[0] = 100
	fmt.Println(b.n, b.data[0], b.data[3], c.data[0])
}
