// Code generated by gencorpus; DO NOT EDIT.
package main

import "fmt"

func main() {
	s := []int{}
	for i := 1; i <= 5; i++ {
		s = append(s, i*i)
	}
	fmt.Println(len(s))
	sum := 0
	for _, v := range s {
		sum += v
	}
	fmt.Println(sum)
}
