#Requires -Version 5.1
<#
.SYNOPSIS
    Verify auto-generated headers in emu/Nt are not stale (INFR-69 guard).

.DESCRIPTION
    `emu/Nt/srv.h` and `emu/Nt/srvm.h` are generated by `limbo -a` /
    `limbo -t Srv` from `module/srvrunt.b`. They MUST be regenerated by
    the active build script for the current target word size — never
    committed by hand from an old build.

    INFR-69 happened because old 32-bit copies (from when
    `emu/Nt/mkfile` declared OBJTYPE=386) were committed, then the
    amd64 build script forgot to regenerate them. The runtime allocated
    a 40-byte F_Srv_iph2a frame while the C struct expected 56-byte
    layout, and DNS resolution AV'd.

    This script regenerates the headers into a temp dir and diffs them
    against the committed copies. Any difference = stale commit.

.PARAMETER LimboPath
    Path to limbo.exe. Defaults to the build output at
    Nt\amd64\bin\limbo.exe.

.EXAMPLE
    .\tests\host\windows-generated-headers-test.ps1

.NOTES
    Related Jira: INFR-69.
    Postmortem:   docs/postmortems/2026-05-14-windows-jit-seh-unwind.md
#>

[CmdletBinding()]
param(
    [string]$LimboPath = ""
)

$ErrorActionPreference = "Stop"

$ROOT = (Get-Location).Path
if (-not $LimboPath) {
    $LimboPath = "$ROOT\Nt\amd64\bin\limbo.exe"
}

if (-not (Test-Path $LimboPath)) {
    Write-Host "FAIL: limbo.exe not found at $LimboPath" -ForegroundColor Red
    Write-Host "Run build-windows-amd64.ps1 first."
    exit 1
}

if (-not (Test-Path "$ROOT\module\srvrunt.b")) {
    Write-Host "FAIL: $ROOT\module\srvrunt.b not found." -ForegroundColor Red
    exit 1
}

$tmpDir = New-Item -ItemType Directory -Path ([System.IO.Path]::GetTempPath()) `
    -Name ("infr69-hdr-check-" + [Guid]::NewGuid().ToString().Substring(0,8)) | Select-Object -ExpandProperty FullName

try {
    # Regenerate headers fresh.
    & $LimboPath -a -I "$ROOT\module" "$ROOT\module\srvrunt.b" 2>$null | Set-Content -Path "$tmpDir\srv.h" -Encoding ASCII
    & $LimboPath -t Srv -I "$ROOT\module" "$ROOT\module\srvrunt.b" 2>$null | Set-Content -Path "$tmpDir\srvm.h" -Encoding ASCII

    $pass = $true
    foreach ($name in @("srv.h", "srvm.h")) {
        $committed = "$ROOT\emu\Nt\$name"
        $fresh = "$tmpDir\$name"

        if (-not (Test-Path $committed)) {
            Write-Host "FAIL: emu/Nt/$name missing from working tree" -ForegroundColor Red
            $pass = $false
            continue
        }

        $diff = Compare-Object `
            -ReferenceObject (Get-Content $committed) `
            -DifferenceObject (Get-Content $fresh)

        if ($diff) {
            Write-Host "FAIL: emu/Nt/$name is stale vs fresh generation" -ForegroundColor Red
            Write-Host "  Committed differs from `limbo -a/-t` output:"
            $diff | Select-Object -First 20 | ForEach-Object {
                $side = if ($_.SideIndicator -eq "<=") { "committed:" } else { "fresh:    " }
                Write-Host "    $side $($_.InputObject)"
            }
            Write-Host ""
            Write-Host "  Fix: regenerate via build-windows-amd64.ps1 (re-runs limbo automatically)"
            Write-Host "  or:  copy `"$fresh`" `"$committed`""
            $pass = $false
        } else {
            Write-Host "OK:   emu/Nt/$name matches fresh limbo output" -ForegroundColor Green
        }
    }

    if ($pass) {
        Write-Host ""
        Write-Host "All generated headers in emu/Nt are current." -ForegroundColor Green
        exit 0
    } else {
        exit 1
    }
} finally {
    Remove-Item -Recurse -Force $tmpDir -ErrorAction SilentlyContinue
}
