<$ROOT/mkconfig

DIRS=\

TARG=\
	about.dis\
	logon.dis\
	clock.dis\
	colors.dis\
	ftree.dis\
	keyring.dis\
	wallet.dis\
	lens.dis\
	man.dis\
	settings.dis\
	editor.dis\
	fractals.dis\
	matrix.dis\
	shell.dis\
	view.dis\
	wm.dis\
	sam.dis\
	samtk.dis\
	samstub.dis\

MODULES=\
	samterm.m\
	samtk.m\
	samstub.m\

SYSMODULES=\
	arg.m\
	bufio.m\
	readdir.m\
	man.m\
	daytime.m\
	draw.m\
	factotum.m\
	formatter.m\
	html.m\
	imagefile.m\
	keyboard.m\
	lucitheme.m\
	math.m\
	matrix.m\
	menu.m\
	menuhit.m\
	plumbmsg.m\
	sh.m\
	string.m\
	styx.m\
	styxservers.m\
	sys.m\
	tk.m\
	tkclient.m\
	webclient.m\
	winplace.m\
	wmclient.m\
	wmlib.m\
	wmsrv.m\

DISBIN=$ROOT/dis/wm

<$ROOT/mkfiles/mkdis
<$ROOT/mkfiles/mksubdirs

