<$ROOT/mkconfig

TARG=\
	rlayout.dis\
	tlayout.dis\
	htmldoc.dis\
	htmlfmt.dis\

MODULES=\
	rlayout.m\
	tlayout.m\

SYSMODULES=\
	sys.m\
	draw.m\
	html.m\
	filter.m\
	mermaid.m\
	pdf.m\
	bufio.m\
	imagefile.m\
	imgload.m\
	htmldoc.m\
	web/charonfs.m\
	formatter.m\

DISBIN=$ROOT/dis/xenith/render

all:V:	$TARG

<$ROOT/mkfiles/mkdis

install:V:	$BINTARG

nuke:V:
	rm -f *.dis *.sbl

clean:V:
	rm -f *.dis *.sbl
