#!/bin/bash
# ─────────────────────────────────────────────────────────────────
# TESTING HARNESS ONLY — NEVER SHIP IN A RELEASE.
#
# CI enforces this:
#   .github/workflows/release.yml refuses to package any file whose
#     name matches serve-agent* or whose path contains agent-harness.
#   .github/workflows/ci.yml refuses any commit that places such a
#     file outside tests/agent-harness/.
#
# Move this file at your peril — see CLAUDE.md "ring-fence rule".
# ─────────────────────────────────────────────────────────────────
#
# serve-agent.sh — Launch the headless agent gateway for the external
# evaluation harness. Exports /mnt/llm (port 5640) and /n/ui (port 5641),
# both bound to 127.0.0.1, with Inferno Ed25519 keyring authentication.
#
# Reuses the serve-llm keyfile at ~/.infernode/lib/keyring/serve-llm,
# generated by `serve-llm.sh --gen-key`. The harness operator and the
# LLM gateway operator share one trust boundary; if you need to separate
# them, generate two keyfiles and edit SERVE_LLM_KEY below.
#
# Usage:
#   serve-agent.sh                  # localhost, keyring auth (default)
#   serve-agent.sh --anon-lan       # localhost, no authentication (debug only)
#   serve-agent.sh --help
#
# Key generation: this script does not generate keys. Run
#   serve-llm.sh --gen-key
# once to produce the shared keyfile.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

case "$(uname -s)" in
	Linux)   EMU="$ROOT/emu/Linux/o.emu" ;;
	Darwin)  EMU="$ROOT/emu/MacOSX/o.emu" ;;
	*)       echo "serve-agent: unsupported platform $(uname -s)" >&2; exit 1 ;;
esac

PROFILE_REL="tests/agent-harness/serve-agent"
PROFILE_HOST="$ROOT/$PROFILE_REL"
PROFILE_INF="/$PROFILE_REL"

# Shared keyfile — same path serve-llm.sh writes / reads.
KEY_HOSTPATH="${HOME}/.infernode/lib/keyring/serve-llm"
KEY_INFPATH="/lib/keyring/serve-llm"

print_help() {
	sed -n '2,32p' "$0" | sed 's/^# \{0,1\}//'
}

LISTEN_MODE="keyring"
for arg in "$@"; do
	case "$arg" in
		--anon-lan) LISTEN_MODE="anon" ;;
		-h|--help)  print_help; exit 0 ;;
		*) echo "serve-agent: unknown arg: $arg (try --help)" >&2; exit 2 ;;
	esac
done

[ -x "$EMU" ]          || { echo "serve-agent: emu missing at $EMU" >&2; exit 1; }
[ -f "$PROFILE_HOST" ] || { echo "serve-agent: profile missing at $PROFILE_HOST" >&2; exit 1; }

if [ "$LISTEN_MODE" = "keyring" ] && [ ! -s "$KEY_HOSTPATH" ]; then
	cat >&2 <<EOF
serve-agent: ERROR no keyfile at $KEY_HOSTPATH

  serve-agent reuses the serve-llm keyfile. Generate it with:
    $ROOT/serve-llm.sh --gen-key

  Or to listen without authentication (loopback only, but still
  unauthenticated — debug use):
    $0 --anon-lan
EOF
	exit 1
fi

export SERVE_LLM_AUTH="$LISTEN_MODE"
export SERVE_LLM_KEY="$KEY_INFPATH"

cat >&2 <<EOF
serve-agent: $(date -Iseconds) starting
  emu     = $EMU
  root    = $ROOT
  profile = $PROFILE_INF
  listen  = $LISTEN_MODE (loopback only)
  /mnt/llm  = tcp!127.0.0.1!5640
  /n/ui   = tcp!127.0.0.1!5641
  keyfile = $KEY_HOSTPATH (in-emu: $KEY_INFPATH)
EOF

exec "$EMU" -c1 "-r$ROOT" sh "$PROFILE_INF"
