// Command gencorpus generates a deterministic, combinatorial corpus of small
// Go programs for the godis differential-testing harness.
//
// Every generated program is a standalone `package main` with deterministic
// output. Output is produced with the fmt package (to stdout) rather than the
// builtin print/println, because the Go spec leaves builtin print formatting
// (notably floats) implementation-defined, which makes it an unreliable
// differential oracle. The programs deliberately avoid floats, goroutine
// scheduling, and map iteration order so that `go run` is reproducible and can
// serve as ground truth.
//
// Usage:
//
//	gencorpus [-out dir]
//
// The default output directory is the _corpus dir relative to the binary (run
// from tools/godis: `go run ./cmd/gencorpus`). Only previously-generated
// gen_*.go files are cleared first — hand-written seed_*.go programs in the same
// directory are left untouched — so the generated corpus is fully reproducible.
// The directory is named with a leading underscore so the go tool ignores it
// (each program is its own package main).
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type prog struct {
	name string
	body string
}

func main() {
	out := flag.String("out", "", "output directory (default: ../../corpus/generated)")
	flag.Parse()

	dir := *out
	if dir == "" {
		dir = filepath.Join("..", "..", "_corpus")
		if _, err := os.Stat("_corpus"); err == nil {
			dir = "_corpus"
		}
	}
	if err := os.MkdirAll(dir, 0o777); err != nil {
		fmt.Fprintln(os.Stderr, "gencorpus:", err)
		os.Exit(1)
	}
	// Clear previously-generated programs for reproducibility.
	matches, _ := filepath.Glob(filepath.Join(dir, "gen_*.go"))
	for _, m := range matches {
		_ = os.Remove(m)
	}

	progs := generate()
	for _, p := range progs {
		path := filepath.Join(dir, "gen_"+p.name+".go")
		if err := os.WriteFile(path, []byte(p.body), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "gencorpus:", err)
			os.Exit(1)
		}
	}
	fmt.Printf("gencorpus: wrote %d programs to %s\n", len(progs), dir)
}

// generate returns the full deterministic program set.
func generate() []prog {
	var ps []prog
	ps = append(ps, sliceProgs()...)
	ps = append(ps, mapProgs()...)
	ps = append(ps, closureProgs()...)
	ps = append(ps, genericProgs()...)
	ps = append(ps, deferProgs()...)
	ps = append(ps, errorProgs()...)
	return ps
}

// header builds a program with the given imports and main body.
func header(imports []string, body string) string {
	var b strings.Builder
	b.WriteString("// Code generated by gencorpus; DO NOT EDIT.\n")
	b.WriteString("package main\n\n")
	switch len(imports) {
	case 0:
	case 1:
		fmt.Fprintf(&b, "import %q\n\n", imports[0])
	default:
		b.WriteString("import (\n")
		for _, im := range imports {
			fmt.Fprintf(&b, "\t%q\n", im)
		}
		b.WriteString(")\n\n")
	}
	b.WriteString("func main() {\n")
	b.WriteString(body)
	b.WriteString("}\n")
	return b.String()
}

func sliceProgs() []prog {
	var ps []prog

	ps = append(ps, prog{"slice_append_len", header([]string{"fmt"}, `	s := []int{}
	for i := 1; i <= 5; i++ {
		s = append(s, i*i)
	}
	fmt.Println(len(s))
	sum := 0
	for _, v := range s {
		sum += v
	}
	fmt.Println(sum)
`)})

	ps = append(ps, prog{"slice_copy", header([]string{"fmt"}, `	src := []int{1, 2, 3, 4}
	dst := make([]int, 2)
	n := copy(dst, src)
	fmt.Println(n, dst[0], dst[1])
`)})

	ps = append(ps, prog{"slice_subslice", header([]string{"fmt"}, `	s := []int{10, 20, 30, 40, 50}
	a := s[1:4]
	fmt.Println(len(a), a[0], a[2])
	b := s[:2]
	fmt.Println(len(b), b[1])
`)})

	ps = append(ps, prog{"slice_2d", header([]string{"fmt"}, `	grid := make([][]int, 3)
	for i := range grid {
		grid[i] = make([]int, 3)
		for j := range grid[i] {
			grid[i][j] = i*3 + j
		}
	}
	total := 0
	for _, row := range grid {
		for _, v := range row {
			total += v
		}
	}
	fmt.Println(total)
`)})

	// Fixed-size value arrays, incl. nested [N][M]T (distinct from slices: laid
	// out contiguously in the frame, indexed by pointer arithmetic).
	ps = append(ps, prog{"array_fixed_2d", header([]string{"fmt"}, `	var a [3][3]int
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			a[i][j] = i*3 + j
		}
	}
	sum := 0
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			sum += a[i][j]
		}
	}
	fmt.Println(sum, a[2][2], a[0][0])
`)})

	return ps
}

func mapProgs() []prog {
	var ps []prog

	// Iterate over sorted keys to keep output deterministic.
	ps = append(ps, prog{"map_count", header([]string{"fmt", "sort"}, `	m := map[string]int{}
	words := []string{"a", "b", "a", "c", "b", "a"}
	for _, w := range words {
		m[w]++
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Println(k, m[k])
	}
`)})

	ps = append(ps, prog{"map_commaok", header([]string{"fmt"}, `	m := map[int]string{1: "one", 2: "two"}
	v, ok := m[1]
	fmt.Println(v, ok)
	_, ok2 := m[9]
	fmt.Println(ok2)
	delete(m, 1)
	fmt.Println(len(m))
`)})

	return ps
}

func closureProgs() []prog {
	var ps []prog

	ps = append(ps, prog{"closure_counter", header([]string{"fmt"}, `	counter := func() func() int {
		n := 0
		return func() int { n++; return n }
	}()
	fmt.Println(counter())
	fmt.Println(counter())
	fmt.Println(counter())
`)})

	ps = append(ps, prog{"closure_accumulate", header([]string{"fmt"}, `	total := 0
	add := func(x int) { total += x }
	for i := 1; i <= 4; i++ {
		add(i)
	}
	fmt.Println(total)
`)})

	// Per-iteration variable capture (Go 1.22+ loop semantics).
	ps = append(ps, prog{"closure_loopvar", header([]string{"fmt"}, `	fns := make([]func() int, 0, 3)
	for i := 0; i < 3; i++ {
		fns = append(fns, func() int { return i })
	}
	for _, f := range fns {
		fmt.Println(f())
	}
`)})

	return ps
}

func genericProgs() []prog {
	var ps []prog

	ps = append(ps, prog{"generic_minmax", header([]string{"fmt"}, `	fmt.Println(gmax(3, 7))
	fmt.Println(gmax("apple", "banana"))
	fmt.Println(gmin(3, 7))
}

type ordered interface {
	~int | ~string
}

func gmax[T ordered](a, b T) T {
	if a > b {
		return a
	}
	return b
}

func gmin[T ordered](a, b T) T {
	if a < b {
		return a
	}
	return b
`)})

	ps = append(ps, prog{"generic_mapfilter", header([]string{"fmt"}, `	in := []int{1, 2, 3, 4, 5}
	doubled := mapper(in, func(x int) int { return x * 2 })
	sum := 0
	for _, v := range doubled {
		sum += v
	}
	fmt.Println(sum)
	evens := filter(in, func(x int) bool { return x%2 == 0 })
	fmt.Println(len(evens), evens[0], evens[1])
}

func mapper[T, U any](s []T, f func(T) U) []U {
	out := make([]U, len(s))
	for i, v := range s {
		out[i] = f(v)
	}
	return out
}

func filter[T any](s []T, keep func(T) bool) []T {
	var out []T
	for _, v := range s {
		if keep(v) {
			out = append(out, v)
		}
	}
	return out
`)})

	return ps
}

func deferProgs() []prog {
	var ps []prog

	ps = append(ps, prog{"defer_order", header([]string{"fmt"}, `	for i := 1; i <= 3; i++ {
		defer fmt.Println("deferred", i)
	}
	fmt.Println("body done")
`)})

	// Defer inside a loop, in a helper, runs at function return (LIFO).
	ps = append(ps, prog{"defer_in_loop", header([]string{"fmt"}, `	fmt.Println(run())
}

func run() int {
	sum := 0
	for i := 0; i < 4; i++ {
		defer func(v int) { sum += v }(i)
	}
	// Defers haven't run yet here; they fire after the return value is fixed.
	return collect()
}

func collect() int {
	n := 0
	defer func() { n = 99 }()
	return n
`)})

	// Named return modified by defer.
	ps = append(ps, prog{"defer_named_return", header([]string{"fmt"}, `	fmt.Println(withDefer())
}

func withDefer() (result int) {
	defer func() { result *= 2 }()
	result = 21
	return result
`)})

	return ps
}

func errorProgs() []prog {
	var ps []prog

	ps = append(ps, prog{"error_new", header([]string{"errors", "fmt"}, `	err := errors.New("boom")
	if err != nil {
		fmt.Println("got:", err.Error())
	}
`)})

	ps = append(ps, prog{"error_wrap", header([]string{"errors", "fmt"}, `	base := errors.New("base failure")
	wrapped := fmt.Errorf("operation failed: %w", base)
	fmt.Println(wrapped.Error())
	if errors.Is(wrapped, base) {
		fmt.Println("is base")
	}
	fmt.Println(errors.Unwrap(wrapped).Error())
`)})

	ps = append(ps, prog{"error_sentinel", header([]string{"errors", "fmt"}, `	_, err := lookup(0)
	if errors.Is(err, errNotFound) {
		fmt.Println("not found")
	}
	v, err := lookup(2)
	if err == nil {
		fmt.Println("ok", v)
	}
}

var errNotFound = errors.New("not found")

func lookup(i int) (int, error) {
	if i == 0 {
		return 0, errNotFound
	}
	return i * 10, nil
`)})

	return ps
}
