<$ROOT/mkconfig

# Charon, the web browser: a window over the engine in appl/lib/web

TARG=\
	charon.dis\

MODULES=\

SYSMODULES=\
	arg.m\
	draw.m\
	lucitheme.m\
	sys.m\
	tk.m\
	tkclient.m\

DISBIN=$ROOT/dis/wm

<$ROOT/mkfiles/mkdis

# its interfaces are the web modules'
WEBMODULES=dom.m html.m css.m style.m fonts.m layout.m page.m browser.m charonfs.m
charon.dis:	${WEBMODULES:%=$ROOT/module/web/%}
