<$ROOT/mkconfig

TARG=\
	t262.dis\
	jsp.dis\
	jsrun.dis\
	jspage.dis\
	jsfuzz.dis\

SYSMODULES=\
	sys.m\
	draw.m\
	readdir.m\
	jslex.m\
	jsparse.m\
	js.m\
	web/dom.m\
	web/css.m\
	web/style.m\
	outlinefont.m\
	web/fonts.m\
	web/layout.m\
	web/page.m\
	web/browser.m\

DISBIN=$ROOT/dis/tests/js

<$ROOT/mkfiles/mkdis
