/*
 * Functions os/port/proc.c calls that live in os/port files not yet
 * imported.
 *
 * Each is marked with the file that owns it upstream. When that file is
 * imported the corresponding definition here must be DELETED, not left
 * to shadow it -- and the linker will insist, since a duplicate symbol
 * is an error rather than a silent preference. That is deliberate: it
 * makes this file self-retiring rather than something to remember.
 *
 * The small primitives are implemented properly rather than stubbed,
 * because a stub that silently does nothing is worse than absent when
 * the caller depends on the effect. The ones that genuinely cannot work
 * yet say so.
 */

#include "u.h"
#include "../port/lib.h"
#include "mem.h"
#include "dat.h"
#include "io.h"
#include "fns.h"
#include "interp.h"

/*
 * Forward declaration rather than including runt.h. srvf2c only takes a
 * Sys_FileIO*, and runt.h is the whole 3500-line generated view of every
 * Dis module interface -- pulling it in here would drag along
 * dependencies (NREG and the keyring types) this file has no use for.
 */
typedef struct Sys_FileIO Sys_FileIO;
#include "../port/error.h"

/*
 * incref, decref, kstrcpy and kstrdup were implemented here.
 * os/port/chan.c now provides them, so they are gone rather than
 * shadowing the real ones.
 */

/*
 * The device table.
 *
 * Normally GENERATED by os/port/mkdevc from the kernel configuration
 * file, which lists the devices this kernel includes. Written by hand
 * until that build machinery exists, and kept here rather than in a
 * "conf.c" precisely so it stays obvious it is a placeholder.
 *
 * Must be nil-terminated: chan.c walks it to resolve a device letter,
 * and devattach indexes it directly. An empty table is not merely
 * useless -- cclose() calls devtab[c->type]->close(c), so a missing
 * entry is a call through nil.
 */
extern Dev rootdevtab;
extern Dev consdevtab;
extern Dev progdevtab;
extern Dev pipedevtab;

Dev*	devtab[] =
{
	&rootdevtab,		/* '/' -- the namespace root */
	&consdevtab,		/* 'c' -- /dev/cons and friends */
	&progdevtab,		/* 'p' -- #p, the process device */
	&pipedevtab,		/* '|' -- #|, pipes */
	nil,
};

/*
 * eve, iseve and seconds were defined here; os/port/devcons.c provides
 * them now.
 *
 * modstatus and dbgexit were here too. os/port/devprog.c provides both,
 * and the linker insisted -- which is what this file is for.
 */

/*
 * Boot-time date, normally read from an RTC. There is none on this
 * board and the VideoCore firmware does not supply the time, so
 * devcons.c's #c/time reports seconds since boot rather than an
 * absolute date it would be inventing.
 */
ulong	kerndate;

/*
 * devcons.c consults this to decide whether console output should also
 * go to a screen. Nothing installs a screenputs yet, so it stays off.
 */
int	consoleprint;


/*
 * Halt. Upstream reboots or returns to a monitor; there is nowhere to
 * return to here, so stop the core with interrupts masked rather than
 * spinning.
 */
void
exit(int code)
{
	USED(code);
	print("\nkernel exit\n");
	splhi();
	for(;;)
		__asm__ volatile("wfi");
}




/*
 * random.c provides the pool; this is the platform entropy source it
 * stirs in. The BCM2837 has a hardware RNG at 0x3F104000 that is worth
 * wiring up -- until then this contributes nothing rather than
 * contributing something predictable, and callers get zeroes they can
 * see rather than randomness they cannot trust.
 */
ulong
genrandom(void)
{
	return 0;
}

/*
 * Platform reset paths devcons.c exposes through #c/reboot and the
 * debug keys. There is no firmware to return to; halting is the honest
 * answer, and exit() already does it.
 */
void
reboot(void)
{
	print("reboot: not supported; halting\n");
	exit(0);
}

void
halt(void)
{
	exit(0);
}


/*
 * portclock.c -- called from inside a contended ilock spin.
 *
 * Upstream uses it to notice that the clock interrupt has been masked
 * for too long while spinning, and to run the timer callbacks that
 * would otherwise be starved. This port drives its tick from clock.c
 * rather than portclock.c's Timer machinery, and runs on one core where
 * a contended ilock means a deadlock rather than a wait -- so there is
 * nothing useful to do here yet, and taslock.c's spin limit is what
 * actually catches the deadlock.
 */
void
clockcheck(void)
{
}

/*
 * modinit -- register the built-in Dis modules.
 *
 * Normally GENERATED by os/port/mkdevc from the "mod" section of the
 * kernel configuration, which for os/pc lists sys, draw, tk, keyring and
 * math. Only sys is built here: the others need their own
 * limbo-generated headers and pull in the whole graphics and crypto
 * stack, none of which a first boot needs.
 *
 * sysmodinit() is what makes the Sys module callable from Dis. Without
 * it a Limbo program cannot open a file or write to the console.
 */
extern void sysmodinit(void);

void
modinit(void)
{
	sysmodinit();
}


/*
 * exportfs.c -- serve a namespace over 9P. Nothing exports anything yet.
 */
int
export(int fd, char *dir, int flag)
{
	USED(fd); USED(dir); USED(flag);
	error("exportfs not imported");
	return -1;
}


/*
 * devsrv.c -- convert a Sys->FileIO channel into a server Chan.
 *
 * inferno.c calls this to implement Sys->file2chan. devsrv is not
 * imported, and unlike the teardown stubs this has a return value a
 * caller would use, so it refuses rather than handing back nil.
 */
Chan*
srvf2c(char *name, char *desc, Sys_FileIO *io)
{
	USED(name); USED(desc); USED(io);
	error("devsrv not imported: file2chan unavailable");
	return nil;
}

/*
 * Discard temporary kernel mappings.
 *
 * portclock.c calls this from the clock interrupt. Ports with a
 * kmap()/kunmap() window for touching physical pages outside the kernel
 * map use it to invalidate that window. This port maps all of RAM
 * identically and never creates one, so there is nothing to discard --
 * and that stays true only while the map is a flat identity.
 */
void
kmapinval(void)
{
}

/*
 * devsrv.c -- the Dis channel types for a served file.
 *
 * devprog.c compares a heap value's type against these when it walks a
 * process's heap, to tell a read/write channel from an ordinary one.
 * devsrv is not imported, so nothing ever creates one: leaving them nil
 * makes that comparison answer "not a served channel", which is both
 * true and the conservative branch. They must be DELETED when
 * devsrv.c lands, and the linker will insist.
 */
Type*	Trdchan;
Type*	Twrchan;

/*
 * devmnt.c -- the 9P mount client.
 *
 * sysfile.c's mount path calls these to negotiate a version and
 * authenticate against a remote server. Reached only through mount(),
 * and nothing mounts anything yet -- but unlike the teardown stubs
 * these have no meaningful empty behaviour: silently reporting a
 * successful version negotiation that never happened would corrupt the
 * protocol state of whatever came next. So they refuse.
 */
Chan*
mntauth(Chan *c, char *spec)
{
	USED(c); USED(spec);
	error("devmnt not imported: cannot authenticate a mount");
	return nil;
}

long
mntversion(Chan *c, char *version, int msize, int returnlen)
{
	USED(c); USED(version); USED(msize); USED(returnlen);
	error("devmnt not imported: cannot negotiate 9P version");
	return 0;
}

/*
 * devmnt.c -- tear down a mount's RPC multiplexer. Nothing mounts
 * anything yet, so there is never a Mnt to close.
 */
void
muxclose(Mnt *m)
{
	USED(m);
}


/*
 * openmode was implemented here. os/port/sysfile.c now provides it.
 */

/*
 * acquire, release, addprog, renameproguser, keepbroken and cflag were
 * all here. os/port/dis.c provides them now -- acquire and release
 * genuinely take the Dis VM lock rather than panicking, which is what
 * they were waiting for.
 */
