<$ROOT/mkconfig

TARG=\
	simple.dis\
	utils.dis\
	mkindex.dis\
	pgw.dis\
	roget.dis\
	wikipedia.dis\
	oeis.dis\
	pg.dis\
	adict.dis\

MODULES=\
	dictm.m\
	dict.m\
	utils.m\

SYSMODULES=\
	bufio.m\

DISBIN=$ROOT/dis/dict


<$ROOT/mkfiles/mkdis

install:V:	$BINTARG $ROOT/dis/dict.dis $ROOT/acme/dis/adict.dis
%.install:V:	$DISBIN/%
%.installall:V:	$DISBIN/%

$ROOT/dis/dict.dis:	dict.dis
	mkdir -p $ROOT/dis
	rm -f $target
	cp dict.dis $target

$ROOT/acme/dis/adict.dis: adict.dis
	mkdir -p $ROOT/acme/dis
	rm -f $target
	cp adict.dis $target

$DISBIN/%:	%.sh
	mkdir -p $DISBIN
	cp $stem.sh $target
	chmod a+rx $target

nuke:V:
	rm -f $ROOT/dis/dict.dis
	rm -f $ROOT/acme/dis/adict.dis
