<$ROOT/mkconfig

TARG=\
	position-table.dis\
	signal-feed.dis\
	risk-gauge.dis\
	alert-watcher.dis\
	llm-recorder.dis\
	llm-context.dis\
	llm-sessions.dis\

SYSMODULES=\
	sys.m\
	draw.m\
	lucitheme.m\
	widget.m\
	matrix.m\

DISBIN=$ROOT/dis/matrix

<$ROOT/mkfiles/mkdis
