<$ROOT/mkconfig

DIRS=\
#	ppp\
#	nppp\

TARG=\
	bootpd.dis\
	ping.dis\
	rip.dis\
	tftpd.dis\
	virgild.dis\
	sntp.dis\
	dhcp.dis\
	wpa.dis\

SYSMODULES=\
	arg.m\
	attrdb.m\
	bufio.m\
	draw.m\
	ether.m\
	factotum.m\
	ip.m\
	ipattr.m\
	keyring.m\
	security.m\
	sys.m\
	wpakey.m\

DISBIN=$ROOT/dis/ip

<$ROOT/mkfiles/mkdis
<$ROOT/mkfiles/mksubdirs
