#!/usr/bin/env python3
"""
Generate the in-kernel root filesystem for a native Inferno kernel.

Stands in for os/port/mkroot. A native kernel has no storage driver at
boot, so its root filesystem IS its image: every file is compiled in as
a byte array, and devroot.c serves them out of two parallel tables.

Usage:  mkrootfs.py OUTPUT.c  ROOTPATH=HOSTFILE ...  ROOTPATH=

A trailing '=' with no host file declares a directory. Parent
directories are created implicitly, so listing /dis/sh.dis is enough.

The layout is not free-form. devroot.c indexes rootdata[] by qid.path
and reads a directory's children as a CONTIGUOUS run of Dirtab entries
(rootdata[q].ptr, .size), so:

  * roottab index must equal qid.path, and
  * every directory's children must be adjacent in the table.

Breadth-first assignment satisfies both: the root takes 0, its children
take the next block, then each of those directories' children take the
block after that.
"""

import sys, os


class Node:
    def __init__(self, name, isdir, host=None):
        self.name = name
        self.isdir = isdir
        self.host = host
        self.kids = {}          # name -> Node, insertion-ordered
        self.qid = None
        self.parent = 0
        self.data = b""


def insert(root, path, host):
    parts = [p for p in path.strip("/").split("/") if p]
    node = root
    for i, part in enumerate(parts):
        last = (i == len(parts) - 1)
        isdir = not last or host is None
        if part not in node.kids:
            node.kids[part] = Node(part, isdir)
        node = node.kids[part]
        if last and host is not None:
            node.isdir = False
            node.host = host
    return node


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: mkrootfs.py OUTPUT.c [ROOTPATH=HOSTFILE|ROOTPATH=]...")

    out = sys.argv[1]
    root = Node("", True)

    for spec in sys.argv[2:]:
        if "=" not in spec:
            sys.exit("mkrootfs: bad spec %r (want ROOTPATH=HOSTFILE)" % spec)
        rootpath, host = spec.split("=", 1)
        insert(root, rootpath, host if host else None)

    # Breadth-first: assign qids so each directory's children are
    # contiguous and index == qid.
    order = [root]
    root.qid = 0
    root.parent = 0
    i = 0
    while i < len(order):
        node = order[i]
        i += 1
        for kid in node.kids.values():
            kid.qid = len(order)
            kid.parent = node.qid
            order.append(kid)

    # Load file contents.
    for node in order:
        if not node.isdir:
            with open(node.host, "rb") as f:
                node.data = f.read()

    with open(out, "w") as f:
        f.write("/*\n")
        f.write(" * GENERATED by tools/mkrootfs.py -- do not edit.\n")
        f.write(" *\n")
        f.write(" * The kernel's root filesystem, compiled into the image.\n")
        f.write(" */\n\n")
        f.write('#include "u.h"\n')
        f.write('#include "../port/lib.h"\n')
        f.write('#include "mem.h"\n')
        f.write('#include "dat.h"\n')
        f.write('#include "fns.h"\n\n')

        for node in order:
            if node.isdir:
                continue
            f.write("static uchar rootdata%d[] = {\n" % node.qid)
            d = node.data
            for j in range(0, len(d), 12):
                f.write("\t" + ",".join("0x%02x" % b for b in d[j:j + 12]) + ",\n")
            f.write("};\n\n")

        f.write("int rootmaxq = %d;\n\n" % len(order))

        f.write("Dirtab roottab[%d] =\n{\n" % len(order))
        for node in order:
            if node.isdir:
                f.write('\t{ "%s",\t{%d, 0, QTDIR},\t0,\t0555 },\n'
                        % (node.name, node.qid))
            else:
                f.write('\t{ "%s",\t{%d, 0, QTFILE},\t%d,\t0555 },\n'
                        % (node.name, node.qid, len(node.data)))
        f.write("};\n\n")

        f.write("Rootdata rootdata[%d] =\n{\n" % len(order))
        for node in order:
            if node.isdir:
                kids = list(node.kids.values())
                if kids:
                    f.write("\t{ %d,\t&roottab[%d],\t%d,\tnil },\n"
                            % (node.parent, kids[0].qid, len(kids)))
                else:
                    f.write("\t{ %d,\tnil,\t0,\tnil },\n" % node.parent)
            else:
                f.write("\t{ %d,\trootdata%d,\t%d,\tnil },\n"
                        % (node.parent, node.qid, len(node.data)))
        f.write("};\n")

    total = sum(len(n.data) for n in order)
    sys.stderr.write("mkrootfs: %d entries, %d bytes of file data\n"
                     % (len(order), total))


if __name__ == "__main__":
    main()
