/*
 * The device table: which devices this board's kernel includes.
 *
 * It was in os/arm64/notyet.c while there was one board, and moved here
 * when a second one (os/virt) had no GPIO, touch panel, SD controller
 * or audio jack to list.
 */
#include "u.h"
#include "../port/lib.h"
#include "mem.h"
#include "dat.h"
#include "fns.h"

/*
 * The device table.
 *
 * Normally GENERATED by os/port/mkdevc from the kernel configuration
 * file, which lists the devices this kernel includes. Written by hand
 * until that build machinery exists.
 *
 * Must be nil-terminated: chan.c walks it to resolve a device letter,
 * and devattach indexes it directly. An empty table is not merely
 * useless -- cclose() calls devtab[c->type]->close(c), so a missing
 * entry is a call through nil.
 */
extern Dev rootdevtab;
extern Dev consdevtab;
extern Dev progdevtab;
extern Dev pipedevtab;
extern Dev usbdevtab;
extern Dev mntdevtab;
extern Dev envdevtab;
extern Dev ipdevtab;
extern Dev pointerdevtab;
extern Dev sddevtab;
extern Dev bootdevtab;
extern Dev benchdevtab;
extern Dev drawdevtab;
extern Dev srvdevtab;
extern Dev etherdevtab;
extern Dev ssldevtab;
extern Dev gpiodevtab;
extern Dev touchdevtab;
extern Dev uartdevtab;
extern Dev audiodevtab;

Dev*	devtab[] =
{
	&rootdevtab,		/* '/' -- the namespace root */
	&consdevtab,		/* 'c' -- /dev/cons and friends */
	&progdevtab,		/* 'p' -- #p, the process device */
	&pipedevtab,		/* '|' -- #|, pipes */
	&usbdevtab,		/* 'u' -- #u, USB endpoints */
	&mntdevtab,		/* 'M' -- #M, the 9P client */
	&envdevtab,		/* 'e' -- #e, the environment */
	&ipdevtab,		/* 'I' -- #I, the IP stack */
	&pointerdevtab,		/* 'm' -- #m, the pointer */
	&sddevtab,		/* 'S' -- #S, the SD card as a file */
	&bootdevtab,		/* 'B' -- #B, the running kernel image */
	&benchdevtab,		/* 'b' -- #b, microsecond timing for benchmarks */
	&drawdevtab,		/* 'i' -- #i, the draw device */
	&srvdevtab,		/* 's' -- #s, names a Limbo program serves */
	&etherdevtab,		/* 'l' -- #l, the kernel Ethernet data path */
	&ssldevtab,		/* 'D' -- #D, SSL/TLS record layer; secstore's transport */
	&gpiodevtab,		/* 'G' -- #G, GPIO pins as files */
	&touchdevtab,		/* 'T' -- #T, the DSI panel's touch buffer */
	&uartdevtab,		/* 't' -- #t, serial ports: eia0 the PL011, eia1 the mini-UART */
	&audiodevtab,		/* 'A' -- #A, /dev/audio: the jack, PWM through DMA (os/bcm2837/audiopwm.c) */
	nil,
};
