/*
 * Functions os/port/proc.c calls that live in os/port files not yet
 * imported.
 *
 * Each is marked with the file that owns it upstream. When that file is
 * imported the corresponding definition here must be DELETED, not left
 * to shadow it -- and the linker will insist, since a duplicate symbol
 * is an error rather than a silent preference. That is deliberate: it
 * makes this file self-retiring rather than something to remember.
 *
 * The small primitives are implemented properly rather than stubbed,
 * because a stub that silently does nothing is worse than absent when
 * the caller depends on the effect. The ones that genuinely cannot work
 * yet say so.
 */

#include "u.h"
#include "../port/lib.h"
#include "mem.h"
#include "dat.h"
#include "io.h"
#include "fns.h"
#include "interp.h"
#include "../port/error.h"

/*
 * incref, decref, kstrcpy and kstrdup were implemented here.
 * os/port/chan.c now provides them, so they are gone rather than
 * shadowing the real ones.
 */

/*
 * The device table.
 *
 * Normally GENERATED by os/port/mkdevc from the kernel configuration
 * file, which lists the devices this kernel includes. Written by hand
 * until that build machinery exists, and kept here rather than in a
 * "conf.c" precisely so it stays obvious it is a placeholder.
 *
 * Must be nil-terminated: chan.c walks it to resolve a device letter,
 * and devattach indexes it directly. An empty table is not merely
 * useless -- cclose() calls devtab[c->type]->close(c), so a missing
 * entry is a call through nil.
 */
extern Dev rootdevtab;

Dev*	devtab[] =
{
	&rootdevtab,
	nil,
};

/*
 * The host owner. With no user model yet there is one principal; this
 * becomes real when devcons and the user machinery are imported.
 */
char*	eve = "inferno";

/*
 * Wall-clock seconds since the epoch, and the boot-time date the kernel
 * was handed. There is no RTC driver and the VideoCore firmware does not
 * provide the time, so this counts from boot rather than pretending to
 * know the date. Returning a monotonically increasing value is what
 * chan.c actually needs (it stamps Chan mtimes); returning a wrong
 * absolute date would be worse than an obviously relative one.
 */
ulong	kerndate;

long
seconds(void)
{
	return (long)(clockticks() / HZ);
}

/*
 * devmnt.c -- the 9P mount client.
 *
 * sysfile.c's mount path calls these to negotiate a version and
 * authenticate against a remote server. Reached only through mount(),
 * and nothing mounts anything yet -- but unlike the teardown stubs
 * these have no meaningful empty behaviour: silently reporting a
 * successful version negotiation that never happened would corrupt the
 * protocol state of whatever came next. So they refuse.
 */
Chan*
mntauth(Chan *c, char *spec)
{
	USED(c); USED(spec);
	error("devmnt not imported: cannot authenticate a mount");
	return nil;
}

long
mntversion(Chan *c, char *version, int msize, int returnlen)
{
	USED(c); USED(version); USED(msize); USED(returnlen);
	error("devmnt not imported: cannot negotiate 9P version");
	return 0;
}

/*
 * devmnt.c -- tear down a mount's RPC multiplexer. Nothing mounts
 * anything yet, so there is never a Mnt to close.
 */
void
muxclose(Mnt *m)
{
	USED(m);
}

/*
 * lib.h's assert() calls this. Upstream puts it in a library; it is
 * here because a failed assertion must be able to report before any
 * console device exists.
 */
void
_assert(char *s)
{
	panic("assert failed: %s", s);
}

/*
 * openmode was implemented here. os/port/sysfile.c now provides it.
 */

/*
 * devcons.c -- print into the console queue.
 *
 * qio.c calls this when a Queue operation needs to report. devcons.c
 * routes it through the console's Queue so it interleaves correctly
 * with everything else on /dev/cons; with no console device yet there
 * is no queue to interleave with, so it goes straight out the UART like
 * print() does.
 */
int
kprint(char *fmt, ...)
{
	va_list arg;
	static char buf[256];

	va_start(arg, fmt);
	vsnprint(buf, sizeof buf, fmt, arg);
	va_end(arg);
	putstrn(buf, strlen(buf));
	return strlen(buf);
}

/*
 * devcons.c
 */
int
iseve(void)
{
	/*
	 * "Is the caller the host owner?" With no user model yet there is
	 * exactly one principal, and it is that one. This becomes a real
	 * check when devcons and the user machinery are imported -- until
	 * then it must not be used to gate anything security-relevant.
	 */
	return 1;
}

int
iprint(char *fmt, ...)
{
	va_list arg;
	static char buf[256];
	int s;

	/*
	 * print() from interrupt context. Masks interrupts rather than
	 * taking the console lock, because the caller may already hold it.
	 */
	s = splhi();
	va_start(arg, fmt);
	vsnprint(buf, sizeof buf, fmt, arg);
	va_end(arg);
	putstrn(buf, strlen(buf));
	splx(s);

	return strlen(buf);
}

/*
 * closepgrp, closefgrp, closesigs and resrcwait were stubbed here.
 * os/port/pgrp.c now provides the real ones, which genuinely tear down
 * a namespace rather than doing nothing, so the stubs are gone.
 *
 * closeegrp still belongs to devenv.c, which is not imported.
 */
void
closeegrp(Egrp *e)
{
	USED(e);
}


/*
 * dis.c -- the Dis VM.
 *
 * acquire/release manage the global VM lock and are only reached by
 * code actually running Dis, so panicking is right: getting there before
 * libinterp is linked means something is running that should not be.
 *
 * addprog is different, and it is worth saying why rather than treating
 * the whole file as one category. newproc() calls it UNCONDITIONALLY
 * for every process, kernel ones included -- but all it does is allocate
 * the per-process Prog and point it at the process's Osenv. It touches
 * no VM state and needs nothing libinterp provides, so it is implemented
 * properly here. Panicking would have made newproc unusable, and a
 * no-op would have left every Proc with a nil prog for something else
 * to trip over later.
 */
void
acquire(void)
{
	panic("acquire: Dis VM not linked yet");
}

void
release(void)
{
	panic("release: Dis VM not linked yet");
}

void
addprog(Proc *p)
{
	Prog *n;

	if((n = p->prog) == nil){
		n = malloc(sizeof(Prog));
		if(n == nil)
			panic("addprog: no memory for Prog");
		p->prog = n;
	} else
		memset(n, 0, sizeof(Prog));
	n->osenv = p->env;
}
