/*
 * Functions os/port/proc.c calls that live in os/port files not yet
 * imported.
 *
 * Each is marked with the file that owns it upstream. When that file is
 * imported the corresponding definition here must be DELETED, not left
 * to shadow it -- and the linker will insist, since a duplicate symbol
 * is an error rather than a silent preference. That is deliberate: it
 * makes this file self-retiring rather than something to remember.
 *
 * The small primitives are implemented properly rather than stubbed,
 * because a stub that silently does nothing is worse than absent when
 * the caller depends on the effect. The ones that genuinely cannot work
 * yet say so.
 */

#include "u.h"
#include "../port/lib.h"
#include "mem.h"
#include "dat.h"
#include "io.h"
#include "fns.h"
#include "interp.h"
#include "../port/error.h"

/*
 * incref, decref, kstrcpy and kstrdup were implemented here.
 * os/port/chan.c now provides them, so they are gone rather than
 * shadowing the real ones.
 */

/*
 * The device table.
 *
 * Normally GENERATED by os/port/mkdevc from the kernel configuration
 * file, which lists the devices this kernel includes. Written by hand
 * until that build machinery exists, and kept here rather than in a
 * "conf.c" precisely so it stays obvious it is a placeholder.
 *
 * Must be nil-terminated: chan.c walks it to resolve a device letter,
 * and devattach indexes it directly. An empty table is not merely
 * useless -- cclose() calls devtab[c->type]->close(c), so a missing
 * entry is a call through nil.
 */
extern Dev rootdevtab;
extern Dev consdevtab;

Dev*	devtab[] =
{
	&rootdevtab,		/* '/' -- the namespace root */
	&consdevtab,		/* 'c' -- /dev/cons and friends */
	nil,
};

/*
 * eve, iseve and seconds were defined here; os/port/devcons.c provides
 * them now.
 */

/*
 * Boot-time date, normally read from an RTC. There is none on this
 * board and the VideoCore firmware does not supply the time, so
 * devcons.c's #c/time reports seconds since boot rather than an
 * absolute date it would be inventing.
 */
ulong	kerndate;

/*
 * devcons.c consults this to decide whether console output should also
 * go to a screen. Nothing installs a screenputs yet, so it stays off.
 */
int	consoleprint;


/*
 * Halt. Upstream reboots or returns to a monitor; there is nowhere to
 * return to here, so stop the core with interrupts masked rather than
 * spinning.
 */
void
exit(int code)
{
	USED(code);
	print("\nkernel exit\n");
	splhi();
	for(;;)
		__asm__ volatile("wfi");
}

/*
 * The JIT flag. os/pc sets this from a "code" section in the kernel
 * configuration; devcons.c reports it through #c/jit. Zero means the
 * Dis interpreter rather than comp-arm64.c, which is the right default
 * until the JIT's icache maintenance is validated on real silicon.
 */
int	cflag;

/*
 * dis.c -- rename the user a Prog runs as. devcons.c calls it when
 * /dev/user is written. No Dis program exists to rename yet.
 */
void
renameproguser(char *old, char *new)
{
	USED(old); USED(new);
}

/*
 * portclock.c -- register a periodic callback on the clock interrupt.
 *
 * devcons.c uses it for keyboard repeat, and dis.c will use it for
 * per-Prog time accounting. This port drives its tick directly from
 * clock.c rather than through portclock.c's Timer machinery, so there
 * is no list to add to yet -- but callers must not silently believe
 * they were registered, hence the report.
 */
Timer*
addclock0link(void (*f)(void), int ms)
{
	USED(f); USED(ms);
	print("addclock0link: portclock.c not imported; %d ms callback ignored\n", ms);
	return nil;
}

/*
 * random.c provides the pool; this is the platform entropy source it
 * stirs in. The BCM2837 has a hardware RNG at 0x3F104000 that is worth
 * wiring up -- until then this contributes nothing rather than
 * contributing something predictable, and callers get zeroes they can
 * see rather than randomness they cannot trust.
 */
ulong
genrandom(void)
{
	return 0;
}

/*
 * Platform reset paths devcons.c exposes through #c/reboot and the
 * debug keys. There is no firmware to return to; halting is the honest
 * answer, and exit() already does it.
 */
void
reboot(void)
{
	print("reboot: not supported; halting\n");
	exit(0);
}

void
halt(void)
{
	exit(0);
}

/*
 * devcons.c consults this to decide whether to keep a broken process
 * around for a debugger rather than reaping it. There is no debugger.
 */
int	keepbroken;

/*
 * devmnt.c -- the 9P mount client.
 *
 * sysfile.c's mount path calls these to negotiate a version and
 * authenticate against a remote server. Reached only through mount(),
 * and nothing mounts anything yet -- but unlike the teardown stubs
 * these have no meaningful empty behaviour: silently reporting a
 * successful version negotiation that never happened would corrupt the
 * protocol state of whatever came next. So they refuse.
 */
Chan*
mntauth(Chan *c, char *spec)
{
	USED(c); USED(spec);
	error("devmnt not imported: cannot authenticate a mount");
	return nil;
}

long
mntversion(Chan *c, char *version, int msize, int returnlen)
{
	USED(c); USED(version); USED(msize); USED(returnlen);
	error("devmnt not imported: cannot negotiate 9P version");
	return 0;
}

/*
 * devmnt.c -- tear down a mount's RPC multiplexer. Nothing mounts
 * anything yet, so there is never a Mnt to close.
 */
void
muxclose(Mnt *m)
{
	USED(m);
}


/*
 * openmode was implemented here. os/port/sysfile.c now provides it.
 */




/*
 * closepgrp, closefgrp, closesigs and resrcwait were stubbed here.
 * os/port/pgrp.c now provides the real ones, which genuinely tear down
 * a namespace rather than doing nothing, so the stubs are gone.
 *
 * closeegrp still belongs to devenv.c, which is not imported.
 */
void
closeegrp(Egrp *e)
{
	USED(e);
}


/*
 * dis.c -- the Dis VM.
 *
 * acquire/release manage the global VM lock and are only reached by
 * code actually running Dis, so panicking is right: getting there before
 * libinterp is linked means something is running that should not be.
 *
 * addprog is different, and it is worth saying why rather than treating
 * the whole file as one category. newproc() calls it UNCONDITIONALLY
 * for every process, kernel ones included -- but all it does is allocate
 * the per-process Prog and point it at the process's Osenv. It touches
 * no VM state and needs nothing libinterp provides, so it is implemented
 * properly here. Panicking would have made newproc unusable, and a
 * no-op would have left every Proc with a nil prog for something else
 * to trip over later.
 */
void
acquire(void)
{
	panic("acquire: Dis VM not linked yet");
}

void
release(void)
{
	panic("release: Dis VM not linked yet");
}

void
addprog(Proc *p)
{
	Prog *n;

	if((n = p->prog) == nil){
		n = malloc(sizeof(Prog));
		if(n == nil)
			panic("addprog: no memory for Prog");
		p->prog = n;
	} else
		memset(n, 0, sizeof(Prog));
	n->osenv = p->env;
}
