<$ROOT/mkconfig

TARG=\
	jslex.dis\
	jsparse.dis\
	jscheck.dis\
	jsre.dis\
	js.dis\

SYSMODULES=\
	sys.m\
	math.m\
	daytime.m\
	jslex.m\
	jsparse.m\
	jscheck.m\
	jsre.m\
	js.m\

DISBIN=$ROOT/dis/lib/js

<$ROOT/mkfiles/mkdis

jsre.dis:	jsrx.b

# js.dis is one module from several fragments
js.dis:	jsval.b jsobj.b jsops.b jscomp.b jsvm.b jsrt.b jsbuiltin.b jsarray.b jsstring.b jscoll.b jsregexp.b jsdate.b jsproxy.b
